/**
 * ===========================================================================
 *  RAFRAÎCHIR LE CERTIFICAT D'AVAST POUR LES CONTENEURS (module 15)
 * ===========================================================================
 *
 *   node docker/n8n/certificat-avast.mjs            vérifie et rafraîchit
 *   node docker/n8n/certificat-avast.mjs --verifier n'écrit rien, dit l'état
 *
 * ───────────────────────────────────────────────────────────────────────────
 *  POURQUOI CE SCRIPT EXISTE : UNE PANNE DE SIX JOURS, SILENCIEUSE.
 * ───────────────────────────────────────────────────────────────────────────
 *
 * L'antivirus de cette machine déchiffre le trafic HTTPS pour l'inspecter,
 * puis le rechiffre avec SA propre autorité. Windows lui fait confiance ;
 * un conteneur Docker, non. On lui monte donc ce certificat, et Node l'ajoute
 * à ses autorités via `NODE_EXTRA_CA_CERTS`.
 *
 * CE CERTIFICAT N'EST PAS STABLE. Son sujet le dit lui-même — « generated by
 * Avast Antivirus for SSL/TLS scanning » : il est fabriqué à l'installation,
 * et REFABRIQUÉ à certaines mises à jour. Le nom ne change pas, la clé si.
 *
 * Le 30 septembre, l'empreinte du magasin Windows ne correspondait plus à
 * celle du fichier extrait le 20. Conséquence : tout appel sortant de n8n
 * échouait sur `UNABLE_TO_VERIFY_LEAF_SIGNATURE`, et donc
 *
 *   - aucune escalade ne partait sur Telegram ;
 *   - l'agent du widget n'atteignait plus Claude, et répondait « un conseiller
 *     va reprendre votre demande » — quatre dossiers en « agent indisponible » ;
 *   - le tunnel refusait de s'ouvrir.
 *
 * Rien ne l'annonçait : chaque garde-fou faisait exactement son travail — ne
 * rien perdre, ne rien inventer — et la panne restait invisible. D'où ce
 * script, et la vérification d'empreinte qu'il rend possible avant chaque
 * séance de travail.
 *
 * ───────────────────────────────────────────────────────────────────────────
 *  CE QU'IL FAIT, ET CE QU'IL NE FAIT PAS
 * ───────────────────────────────────────────────────────────────────────────
 *
 *   1. lit l'autorité d'Avast dans le magasin de Windows (lecture seule) ;
 *   2. compare son empreinte à celle du fichier du dépôt ;
 *   3. si elles diffèrent, réécrit `certificats/avast-root.crt` ;
 *   4. reconstruit `certificats/faisceau-avec-avast.crt` — les autorités
 *      publiques du conteneur, plus celle d'Avast — dont le tunnel a besoin ;
 *   5. dit s'il faut redémarrer le conteneur.
 *
 * IL NE DÉSACTIVE JAMAIS LA VÉRIFICATION TLS. `NODE_TLS_REJECT_UNAUTHORIZED=0`
 * ferait taire le symptôme en supprimant la garantie : n8n accepterait alors
 * n'importe quel certificat, y compris celui d'un intercepteur hostile. Ici,
 * on ajoute UNE autorité nommée, et l'on vérifie qu'elle est la bonne.
 *
 * CE CERTIFICAT EST PUBLIC — une clé publique, pas un secret. Il reste
 * néanmoins hors du dépôt : il décrit cette machine, pas le projet. Sur une
 * machine sans antivirus intercepteur, rien de tout ceci n'est nécessaire.
 *
 * EN PRODUCTION, CE SCRIPT N'A AUCUN RÔLE. Un serveur n'a pas d'antivirus qui
 * intercepte le TLS : `docker-compose.yml` y suffit, seul, et le certificat
 * comme la surcharge restent sur le poste de développement.
 * ===========================================================================
 */

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { X509Certificate } from 'node:crypto';

const DOSSIER = fileURLToPath(new URL('./certificats/', import.meta.url));
const RACINE = `${DOSSIER}avast-root.crt`;
const FAISCEAU = `${DOSSIER}faisceau-avec-avast.crt`;

const CONTENEUR = 'coachconnect-n8n';
const VERIFIER_SEULEMENT = process.argv.includes('--verifier');

/** Empreinte lisible d'un certificat au format PEM. */
function empreinteDe(pem) {
  try {
    return new X509Certificate(pem).fingerprint256;
  } catch {
    return null;
  }
}

/**
 * L'autorité d'Avast, lue dans le magasin de Windows.
 *
 * `Cert:\LocalMachine\Root` D'ABORD : c'est le magasin de la machine, celui
 * qu'Avast alimente à l'installation. Le magasin de l'utilisateur en porte une
 * copie, mais la machine est la source.
 */
function racineDeWindows() {
  const ps = [
    "$c = Get-ChildItem Cert:\\LocalMachine\\Root, Cert:\\CurrentUser\\Root -ErrorAction SilentlyContinue |",
    "  Where-Object { $_.Subject -match 'Avast Web/Mail Shield Root' } | Select-Object -First 1;",
    'if (-not $c) { Write-Output "ABSENT"; exit 0 }',
    '"-----BEGIN CERTIFICATE-----`r`n" +',
    "  [Convert]::ToBase64String($c.RawData,'InsertLineBreaks') +",
    '  "`r`n-----END CERTIFICATE-----"',
  ].join(' ');

  const r = spawnSync('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', ps], {
    encoding: 'utf8',
    windowsHide: true,
  });

  const sortie = `${r.stdout ?? ''}`.trim();
  if (r.status !== 0) throw new Error(`lecture du magasin Windows impossible : ${r.stderr ?? r.status}`);
  if (sortie === 'ABSENT' || !sortie.includes('BEGIN CERTIFICATE')) return null;

  // Fins de ligne normalisées : le fichier est relu par des outils Linux.
  return `${sortie.replace(/\r\n/g, '\n').trim()}\n`;
}

/**
 * Les autorités publiques du conteneur, pour reconstruire le faisceau.
 *
 * LE TUNNEL EST UN BINAIRE Go, et Go REMPLACE tout son magasin par le fichier
 * que désigne `SSL_CERT_FILE`. Ne lui donner que le certificat d'Avast rendrait
 * le reste d'Internet invérifiable : il lui faut le faisceau complet.
 */
function faisceauPublic() {
  const r = spawnSync('docker', ['exec', CONTENEUR, 'cat', '/etc/ssl/certs/ca-certificates.crt'], {
    encoding: 'utf8',
    maxBuffer: 16 * 1024 * 1024,
    windowsHide: true,
  });
  if (r.status !== 0 || !`${r.stdout ?? ''}`.includes('BEGIN CERTIFICATE')) return null;
  return `${r.stdout.replace(/\r\n/g, '\n').trim()}\n`;
}

/* ================================================================== *
 *  DÉROULÉ
 * ================================================================== */

if (!existsSync(DOSSIER)) mkdirSync(DOSSIER, { recursive: true });

const duDepot = existsSync(RACINE) ? readFileSync(RACINE, 'utf8') : null;
const empreinteDepot = duDepot ? empreinteDe(duDepot) : null;

const deWindows = racineDeWindows();

if (!deWindows) {
  console.log('Aucune autorité « Avast Web/Mail Shield Root » dans le magasin de Windows.');
  console.log('Cette machine n’intercepte donc pas le HTTPS : la surcharge Docker est inutile ici.');
  process.exit(0);
}

const empreinteWindows = empreinteDe(deWindows);
const court = (e) => (e ? `${e.replace(/:/g, '').slice(0, 16)}…` : 'aucune');

console.log(`empreinte dans Windows : ${court(empreinteWindows)}`);
console.log(`empreinte du dépôt     : ${court(empreinteDepot)}`);

if (empreinteWindows === empreinteDepot) {
  console.log('\nÀ JOUR : le conteneur connaît la bonne autorité. Rien à faire.');

  // Le faisceau peut manquer même quand la racine est bonne (dépôt neuf).
  if (!existsSync(FAISCEAU) && !VERIFIER_SEULEMENT) {
    const publiques = faisceauPublic();
    if (publiques) {
      writeFileSync(FAISCEAU, `${publiques}${deWindows}`);
      console.log('Faisceau reconstruit (il manquait) : certificats/faisceau-avec-avast.crt');
    }
  }
  process.exit(0);
}

console.log('\nPÉRIMÉ : Avast a régénéré son autorité — même nom, clé différente.');
console.log('Tant que le conteneur ne connaît pas la nouvelle, TOUT appel HTTPS sortant');
console.log('de n8n échoue sur UNABLE_TO_VERIFY_LEAF_SIGNATURE : Telegram, Claude, le tunnel.');

if (VERIFIER_SEULEMENT) {
  console.log('\n--verifier : aucun fichier n’a été modifié.');
  process.exit(1);
}

writeFileSync(RACINE, deWindows);
console.log('\nÉcrit : certificats/avast-root.crt');

const publiques = faisceauPublic();
if (publiques) {
  writeFileSync(FAISCEAU, `${publiques}${deWindows}`);
  const nombre = (publiques.match(/BEGIN CERTIFICATE/g) ?? []).length;
  console.log(`Écrit : certificats/faisceau-avec-avast.crt (${nombre} autorités publiques + Avast)`);
} else {
  console.log('Faisceau NON reconstruit : le conteneur n8n doit tourner pour en lire les autorités.');
}

/*
 * `NODE_EXTRA_CA_CERTS` EST LU AU DÉMARRAGE DU PROCESSUS. Le fichier est monté,
 * donc son nouveau contenu est déjà visible dans le conteneur — mais Node a
 * chargé l'ancien en mémoire. Un redémarrage suffit ; recréer le conteneur
 * n'est pas nécessaire, la surcharge n'ayant pas changé.
 */
console.log('\nÀ FAIRE MAINTENANT : docker restart coachconnect-n8n');
console.log('(Node lit ce certificat au démarrage ; sans redémarrage, il garde l’ancien.)');
